import { SkillCategory } from '../types'

const category: SkillCategory = {
  id: 'skills:backend',
  label: 'Backend development',
  skills: [
    'Spring',
    'Java',
    'JavaSE',
    'Hibernate',
    'Server',
    'Kubernetes',
    'Websocket',
    'Docker',
    'RabbitMQ',
    'Kafka',
    'Zookeeper',
    'Go',
    'Apache',
    'Httpd',
    'Nginx',
    'SSL',
    'HTTPS',
    'HTTP',
    'GWT',
    'AWS',
    'AWS Lambda',
    'Websphere',
    'Java EE',
    'Cloud Computing',
    'MicroServices',
    'API',
    'XML',
    'JSON',
    'REST',
    'NodeJS',
    'Kibana',
    'Cluster',
    'Datacenter',
    'K8s',
    'Azure',
    'Google Cloud',
    'Node.js',
    'Oracle',
    'Maven',
    'Log4j',
    'J2SE',
    'J2EE',
    'Tomcat',
    'Jetty',
    'Wicket',
    'Ant',
    'Ivy',
    'ASP.NET',
    'Unix',
    'Services',
    'JSP',
    'Amazon',
    'Django',
    'Servlets',
    'JVM',
    'CUDA',
    'OpenCL',
    'Vaadin',
    'RESTful',
    'ProtoBuf',
    'Memcached',
    'Glassfish',
    'SOAP Services'
  ]
}
export default category
