import { SkillCategory } from '../types'

const category: SkillCategory = {
  id: 'skills:backend',
  label: 'Backend development',
  skils: [
    'Spring',
    'Java',
    'Hibernate',
    'Server',
    'Kubernetes',
    'Websocket',
    'Docker',
    'MongoDB',
    'ElasticSearch',
    'LogStash',
    'PostgreSQL',
    'RabbitMQ',
    'Kafka',
    'Zookeeper',
    'Go',
    'Apache',
    'Httpd',
    'Nginx',
    'SSL',
    'HTTPS',
    'HTTP',
    'GWT',
    'AWS',
    'AWS Lambda',
    'Websphere',
    'Java EE',
    'Cloud Computing',
    'MicroServices',
    'Redis',
    'API',
    'XML',
    'JSON',
    'REST',
    'MYSQL',
    'NodeJS',
    'Kibana',
    'Cluster',
    'Datacenter',
    'K8s',
    'Azure',
    'Google Cloud',
    'Node.js',
    'Oracle',
    'Maven',
    'Log4j',
    'J2SE',
    'J2EE',
    'Tomcat',
    'Jetty',
    'Wicket',
    'Ant',
    'Ivy'
  ]
}
export default category
