import { SkillCategory } from '../types'

const category: SkillCategory = {
  id: 'skills:programming-languages',
  label: 'Programming Languages',
  skills: [
    'Python',
    'C',
    'C/C++',
    '.NET',
    'Java',
    'C++',
    'C#',
    'Visual Basic',
    'JavaScript',
    'PHP',
    'Assembly',
    'SQL',
    'Go',
    'Swift',
    'R',
    'MATLAB',
    'Delphi',
    'Object Pascal',
    'Ruby',
    'Classic Visual Basic',
    'Objective-C',
    'Perl',
    'Groovy',
    'SAS',
    'Scratch',
    'Fortran',
    'Rust',
    '(Visual) FoxPro',
    'COBOL',
    'Dart',
    'Kotlin',
    'Lua',
    'Julia',
    'Prolog',
    'Ada',
    'PL/SQL',
    'ABAP',
    'Lisp',
    'D',
    'Scala',
    'TypeScript',
    'VBScript',
    'LabVIEW',
    'Scheme',
    'Awk',
    'Ladder Logic',
    'Apex',
    'PowerShell',
    'Logo',
    'Haskell',
    'Bash',
    'RPG',
    'ML',
    'Oracle PL/SQL',
    'XSLT',
    'Erlang',
    'Golang'
  ]
}
export default category
