import { SkillCategory } from '../types'

const category: SkillCategory = {
  id: 'skills:management',
  label: 'Management',
  skills: [
    'Agile',
    'Business Development',
    'Charisma',
    'Dealing with work-related stress',
    'ERP',
    'Feature Definition',
    'Financial Modelling',
    'Forecasting',
    'Ideation Leadership',
    'Innovation',
    'Management',
    'Managerial Skills',
    'Managing Cross-Functional Teams',
    'Meeting Facilitation',
    'Motivation',
    'Negotiation',
    'Organizing Skills',
    'People management',
    'Performance Tracking',
    'Planning',
    'Problem-solving',
    'Profit and Loss',
    'Project Lifecycle Management',
    'Proposal writing',
    'Requirements Analysis',
    'Scope Management',
    'Scrum',
    'Strategic Management',
    'Task delegation',
    'Technological savviness',
    'Emotional Intelligence',
    'Управление проектами',
    'Проектирование',
    'UML',
    'JIRA',
    'Requirements'
  ]
}
export default category
